### ISSUE TITLE
guide how to run

### ISSUE THREAD

**Issue by Jacknq** [mgyongyosi/VuejsSSRSample#4]
guide how to run is missing.. 
npm install 
dotnet run  are clear to me but it doesnt work yet.. 
Is it really problem putting exact steps in readme how to run this?

**Comment by mgyongyosi** [comment]
Nope, it's not a problem. I haven't included it here, because the article contains the required steps to build the bundles. Anyway, I've included the required devDependencies in the `package.json` to make it easier to run the sample. Update your `master` and try with the following commands. If it still doesn't work let me know.
```
npm install
npm run build
dotnet run
```

**Comment by Jacknq** [comment]
Thanks for info.
You didnt put webpack in dependencies yet  therefore it still wont work, since it doesnt know webpack and its version.
